
#General settings
[General]
	#
	#Range: > 0
	gracePeriod = 6000
	#Defines the amount of time in seconds in which the captcha should be solved [Default: 15]
	#Range: > 1
	captchaTime = 10
	#Defines the cooldown between captcha requests in seconds [Default: 900 (15 minutes)]
	#Range: > 30
	captchaCooldown = 1800

#Math settings
[Math]
	#Defines the max the first number can be in the addition problem [Default: 100]
	#Range: > 1
	additionMaxX = 100
	#Defines the max the second number can be in the addition problem [Default: 100]
	#Range: > 30
	additionMaxY = 100
	#Defines the max the first number can be in the subtraction problem [Default: 100]
	#Range: > 1
	subtractionMaxX = 100
	#Defines the max the second number can be in the subtraction problem [Default: 100]
	#Range: > 30
	subtractionMaxY = 100
	#Defines the max the first number can be in the multiplication problem [Default: 20]
	#Range: > 1
	multiplicationMaxX = 20
	#Defines the max the second number can be in the multiplication problem [Default: 20]
	#Range: > 20
	multiplicationMaxY = 20
	#Defines the max the first number can be in the division problem [Default: 100]
	#Range: > 1
	divisionMaxX = 100
	#Defines the max the second number can be in the division problem [Default: 100]
	#Range: > 30
	divisionMaxY = 100

#Text settings
[Text]
	#List of words that can be used to generate a text captcha (16 character length max)
	textCaptchaWords = ["fundies", "john", "baby john", "limburger", "three-cheese", "comedy", "gaming", "eric's toy", "updog", "room 40", "poppengamer", "ratlantis", "dweller", "herobrine", "schmoe", "philly fries", "serified", "true love", "homecoming", "pickles", "the burger", "bonk", "lap3lap3lap3", "mega john", "hhgregg", "bumblezone", "1987"]

