#Enable/Disable Cleavers
#Caverns and Chasms
#Disable Silver cleaver (Default: false)
silver_cleaver_disable = false
#Disable Necroimum cleaver (Default: false)
ccnecromium_cleaver_disable = false
#
#Oreganized
#Disable Lead cleaver (Default: false)
olead_cleaver_disable = false
#Disable Electrum cleaver (Default: false)
oelectrum_cleaver_disable = false
#
#Applied Energistics 2
#Disable Certus Quartz cleaver (Default: false)
certus_quartz_cleaver_disable = false
#Disable Nether Quartz cleaver (Default: false)
nether_quartz_cleaver_disable = false
#Disable Fluix cleaver (Default: false)
fluix_cleaver_disable = false
#
#Forbidden and Arcanus
#Disable Draco Arcanus cleaver (Default: false)
draco_arcanus_cleaver_disable = false
#Disable Reinforced Deorum cleaver (Default: false)
reinforced_deorum_cleaver_disable = false
#
#Gobber
#Disable Gobber cleaver (Default: false)
gobber_cleaver_disable = false
#Disable Nether Gobber cleaver (Default: false)
gobber_nether_cleaver_disable = false
#Disable End Gobber cleaver (Default: false)
gobber_end_cleaver_disable = false
#
#Embers Rekindled
#Disable Lead cleaver (Default: false)
elead_cleaver_disable = false
#Disable Silver cleaver (Default: false)
esilver_cleaver_disable = false
#Disable Dawnstone cleaver (Default: false)
dawnstone_cleaver_disable = false
#
#Other mods
#Disable Rose Gold cleaver from Deeper Caves (Default: false)
dcrose_gold_cleaver_disable = false
#Disable Enderite cleaver from Enderite Mod (Default: false)
enderite_cleaver_disable = false
#Disable Kobold Iron cleaver from Kobolds! (Default: false)
kobold_iron_cleaver_disable = false
#Disable Neptunium cleaver from Aquaculture 2 (Default: false)
neptunium_cleaver_disable = false
#Currently obtaining a Silex cleaver can't be disabled as it's obtained through loot tables
#Hide Silex cleaver from Sweety's Archaeology (Default: false)
silex_cleaver_disable = false

