
[General]
	#The number of minutes until you get tired. 20 minutes is one day-night cycle. (dafault: 40)
	minutes_until_tired = 40.0
	#If you will die from exhaustion or remain on one heart. (defaultl: True)
	die_from_exhaustion = true
	#Number of ticks a phase should last.
	phase_time_ticks = 6000.0

